load '../../build-support/dependencies.rb'

platform :ios, '13.0'
use_frameworks!

include_build_tools!

target 'AWSLocationPlugin' do
    pod 'Amplify', :path => '../../'
    pod 'AWSPluginsCore', :path => '../../'
    pod "AWSLocation", $OPTIMISTIC_AWS_SDK_VERSION
end

target "HostApp" do
    use_frameworks!
    include_test_utilities!

    pod 'AmplifyTestCommon', :path => '../../'
    pod 'Amplify', :path => '../../'
    pod 'AWSPluginsCore', :path => '../../'
    
    target "AWSLocationPluginIntegrationTests" do
        pod 'AmplifyPlugins/AWSCognitoAuthPlugin', :path => '../../'

        inherit! :complete
    end

    target "AWSLocationPluginTests" do
        inherit! :complete
    end
end
